site_name: FOR5596 Research Data Management Ressources
repo_url: https://github.com/FOR5596/rdm-website
repo_name: FOR5596/rdm-website
site_url: https://FOR5596.github.io/rdm-website/
site_author: Max Häußler


nav:
  - Home: index.md
  - Research Data Models:
    - Define a RDM: rdm/define.md
  - Installations:
    - Docker: installations/docker.md
    - Local Jupyter Notebook: installations/jupyternotebook.md
    - Setup Local Programming Environment: installations/local_env.md


theme:
  name: material
  logo: images/FOR5596_square.png
  features:
    - navigation.instant
    - navigation.instant.preview
    - navigation.instant.prefetch
    - navigation.indexes
    - navigation.footer
    - content.action.view
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - content.tabs.links
    - content.code.select
    - content.code.copy
    - content.code.annotation
    - content.tooltips
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode


markdown_extensions:
  - abbr
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - admonition
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md

  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
